add README.jp.md
spectresystems/spectre.console pull request #112
Opened 2020-10-18 09:10 UTC by yamatoya

https://github.com/spectresystems/spectre.console/pull/107

I add a localized README for Japanese.

2020-10-18 09:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=112) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=112) before we can accept your contribution.<br/><hr/>**Takahito Yamatoya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spectresystems/spectre.console?pullRequest=112) it.</sub>

2020-10-18 20:22 UTC, patriksvensson requested changes
Awesome work!

Don't we need to update the anchor (like `2. [例](#example)`) for the links to work as well?

2020-10-18 20:22 UTC, patriksvensson commented on README.jp.md
> +### static APIの利用
```suggestion
### Static APIの利用
```

2020-10-18 20:22 UTC, patriksvensson commented on README.jp.md
> +   3.1. [static APIの利用](#using-the-static-api)
```suggestion
   3.1. [Static APIの利用](#using-the-static-api)  
```

2020-10-18 20:22 UTC, patriksvensson commented on README.jp.md
> +   3.2. [consoleの作成](#creating-a-console)
I can't find this header below, did you forget to change this one?

2020-10-18 20:23 UTC, patriksvensson requested changes

2020-10-18 20:23 UTC, patriksvensson commented on README.jp.md
> +   3.2. [consoleの作成](#creating-a-console)
```suggestion
   3.2. [Consoleの作成](#creating-a-console)
```

2020-10-19 00:52 UTC, yamatoya commented on README.jp.md
> +   3.2. [consoleの作成](#creating-a-console)
I fix.

2020-10-19 13:42 UTC, merged