to add how to install
spectresystems/spectre.console pull request #114
Opened 2020-10-18 09:58 UTC by yamatoya

2020-10-18 20:07 UTC, patriksvensson requested changes

2020-10-18 20:07 UTC, patriksvensson commented on README.md
> +
Can we remove this empty line?

2020-10-19 00:34 UTC, yamatoya commented on README.md
> +
Yes, I done.

2020-10-19 14:50 UTC, patriksvensson approved these changes

2020-10-19 14:50 UTC, merged