add Chinese README
spectresystems/spectre.console pull request #148
Opened 2020-11-25 05:30 UTC by chenxuuu

Simplified Chinese
简体中文

2020-11-25 05:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spectresystems/spectre.console?pullRequest=148) it.</sub>

2020-11-26 19:07 UTC, nafeef123 approved these changes

2020-11-26 19:08 UTC, nafeef123 approved these changes

2020-11-30 02:20 UTC, patriksvensson requested changes
Thanks for this translation!
The translation is however out-of-date and needs to be updated to reflect the current version.

2020-11-30 03:41 UTC, chenxuuu commented
@patriksvensson done.

2020-11-30 04:55 UTC, patriksvensson approved these changes

2020-11-30 04:56 UTC, merged

2020-11-30 04:56 UTC, patriksvensson commented
Merged! Sorry for taking so long.
Thank you for your contribution. Much appreciated! 👍