Interlaced Canvas Graphics
spectresystems/spectre.console pull request #153
Opened 2020-11-29 18:01 UTC by rogeralsing

Proof of Concept PR for interlaced graphics.
The idea is that Canvas has a `CanvasRenderMode` which decides if it renders using a full ' ' space block, or if it uses a '▄' char with fore and back-color to get two pixels in one char.

No idea if this is something that is of value for the project, but it was fun to play with :-)

**Before:**
<img width="598" alt="Skärmavbild 2020-11-29 kl  18 46 05" src="https://user-images.githubusercontent.com/647031/100549486-72961b80-3273-11eb-82de-fc2a0037c7b6.png">

**After:**
<img width="584" alt="Skärmavbild 2020-11-29 kl  18 58 43" src="https://user-images.githubusercontent.com/647031/100549716-f8ff2d00-3274-11eb-95c2-e13ab9bcb2ba.png">

2020-11-29 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spectresystems/spectre.console?pullRequest=153) it.</sub>

2020-11-30 02:19 UTC, patriksvensson requested changes
A very cool feature. Left a couple of comment that needs to be fixed (together with the warnings and errors) before it can be merged.

Great job!

2020-11-30 02:19 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Canvas.cs
> +            return RenderMode switch
We need to take into account if the console doesn't support Unicode here or is a Windows legacy console, and not use interlaced mode in that case.

```csharp
if(!context.Unicode || context.LegacyConsole) {
   // ...
}
```

2020-11-30 02:19 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Canvas.cs
> +        public int PixelWidth { get; set; } = 1;
`PixelWidth` should default to `2`

2020-11-30 02:19 UTC, patriksvensson commented on examples/Canvas/Program.cs
>          private static void Render(IRenderable canvas, string title)
Can we leave the example as-is for now?

2020-11-30 08:58 UTC, rogeralsing commented
Maybe it would make more sense to have a ICanvasRenderer interface instead of the RenderMode enum?

Where the ICanvasRenderer takes the canvas data and translate it to ascii/unicode depending on its own implementation.

That would open up for 3rd party renderers that don't have to go into the lib itself.

less impact, more flexibility.

It would open up to do things like this:
<img width="557" alt="Skärmavbild 2020-11-30 kl  09 55 48" src="https://user-images.githubusercontent.com/647031/100588579-571e2580-32f2-11eb-8c35-33bbf44c32d9.png">

(From a Java tool, TerminalImageViewer)

Maybe nothing useful but still fun to have the ability to plug such thing in.

2020-12-07 16:01 UTC, patriksvensson commented
@rogeralsing Sorry for the late reply.

I think it's OK to leave it as it is right now, and we can create an abstraction if a need for a new renderer arises.

2020-12-30 09:16 UTC, patriksvensson commented
@rogeralsing Closing this for now. Feel free to reopen if you want to continue working on this 👍🏻

2020-12-30 09:16 UTC, closed without merging