fix nullability in type conversion
spectresystems/spectre.console pull request #181
Opened 2020-12-24 01:43 UTC by SimonCropp

2020-12-24 01:44 UTC, SimonCropp commented on src/Spectre.Console/Internal/TypeConverterHelper.cs
> -            if (converter != null)
TypeDescriptor.GetConverter doesnt return null. so this method is redundant

2020-12-24 01:45 UTC, SimonCropp commented on src/Spectre.Console/Internal/TypeConverterHelper.cs
> +                return result != null;
checking result for null here means we can `NotNullWhen(true)` for the out. so calling methods can use the result without an extra null check

2020-12-31 10:08 UTC, patriksvensson commented
@SimonCropp I've rebased this branch against upstream for you, waiting for CI to pass

2020-12-31 10:15 UTC, patriksvensson approved these changes
LGTM!

2020-12-31 10:18 UTC, patriksvensson requested changes
Just noticed that the `GetTypeConverter` has been removed which it shouldn't.

2020-12-31 10:18 UTC, patriksvensson commented on src/Spectre.Console/Internal/TypeConverterHelper.cs
> -            if (converter != null)
This method is actually needed. We're not only getting the TypeConverter for the explicit type, but we also check the type if it has a `TypeConverterAttribute` assigned and instantiate that one otherwise.

2021-01-08 08:57 UTC, SimonCropp commented
think it is easier to restart this one

2021-01-08 08:57 UTC, closed without merging