enables returning a result from StartAsync
spectresystems/spectre.console pull request #208
Opened 2021-01-04 17:42 UTC by thoemmi

This PR adds overloads to `StartAsync` which accept delegates returning a generic `Task<T>`.

E.g. this allows to show a spinner while fetching data:

```csharp
var data = AnsiConsole.Status()
    .Spinner(Spinner.Known.Star)
    .StartAsync("Fetching data...", async ctx => {
        var r = await _client.FetchDataAsync();
        return r;
    });
```

The code is mainly a copy of the existing functions but returning a generic `Task<T>`.

2021-01-05 13:12 UTC, patriksvensson requested changes

2021-01-05 13:12 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Progress/Progress.cs
> +        public async Task<T> StartAsync<T>(Func<ProgressContext, Task<T>> action)
This method duplicates a lot of code in `Task StartAsync(Func<ProgressContext, Task> action)`. Could we perhaps call this function from the other one with a dummy `object` parameter and discard the result?

2021-01-05 13:12 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Progress/Status.cs
> +        public async Task<T> StartAsync<T>(string status, Func<StatusContext, Task<T>> action)
This method duplicates a lot of code in `Task StartAsync(string status, Func<StatusContext, Task> action)`. Could we perhaps call this function from the other one with a dummy `object` parameter and discard the result?

2021-01-05 13:42 UTC, thoemmi commented on src/Spectre.Console/Widgets/Progress/Progress.cs
> +        public async Task<T> StartAsync<T>(Func<ProgressContext, Task<T>> action)
That bothered me too, but I didn't find a solution. However, after rethinking it again, I think I have resolved the duplication.

2021-01-06 07:07 UTC, patriksvensson approved these changes

2021-01-06 07:08 UTC, merged