Add cycle detection to tree rendering
spectresystems/spectre.console pull request #224
Opened 2021-01-13 08:44 UTC by mcon

In the existing code, cycles will result in an infinite loop in execution, this PR results in an exception being raised in stead.

It's tricky reporting the error in a useful way: i.e. "this is the node that's causing problems", given that would involve rendering the node, and including that information in the exception rather than printing to console, would involve using a fake console, which would be all very strange. Certainly this is better than the previous state of affairs, let me know if you have any ideas here.

2021-01-13 18:51 UTC, patriksvensson commented
@mcon Ready for review?

2021-01-14 07:42 UTC, patriksvensson requested changes

2021-01-14 07:42 UTC, patriksvensson commented on src/Spectre.Console.Tests/Unit/TreeTests.cs
> +            Should.Throw<CircularTreeException>(() => console.Render(tree));
```suggestion
            // When
            var result = Record.Exception(() => console.Render(tree));
            
            // Then
            result.ShouldBeOfType<CircularTreeException>();
```

2021-01-14 07:42 UTC, patriksvensson commented on src/Spectre.Console.Tests/Unit/TreeTests.cs
> +        public void Tree_With_Cycle_Throws()
```suggestion
        public void Should_Throw_If_Tree_Contains_Cycles()
```

2021-01-14 16:41 UTC, patriksvensson approved these changes

2021-01-14 16:42 UTC, patriksvensson commented
@mcon There are merge conflicts in the PR branch. Could you resolve them and I'll merge. Thanks 👍🏻

2021-01-14 17:19 UTC, mcon commented
Doesn't look like there are any conflicts to me...

2021-01-14 17:37 UTC, merged

2021-01-14 17:37 UTC, patriksvensson commented
Ah, couldn't rebase and merge due to conflict in individual commits. Squashing went fine.

2021-01-14 17:38 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍