Customize SelectionPrompt selected choice color
spectresystems/spectre.console pull request #233
Opened 2021-01-14 13:29 UTC by NickWingate

Currently the highlight color for the selected choice in SelectionPrompt and MultiSelectionPrompt is always blue and can result in visibility problems on black backgrounds:
![image](https://user-images.githubusercontent.com/46056725/104596340-c74af580-566b-11eb-84ca-fb791e394ef2.png)

Can now be changed by using `.HighlightColor(Color.Red)` for example making it easier to see and more customizable:

![image](https://user-images.githubusercontent.com/46056725/104596761-52c48680-566c-11eb-990a-f2a76110a583.png)

Example in context:
```cs
fruit = AnsiConsole.Prompt(
        new SelectionPrompt<string>()
            .Title("Ok, but if you could only choose [green]one[/]?")
            .AddChoices(favorites)
            .HighlightColor(Color.Red));
```

2021-01-14 13:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=233) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spectresystems/spectre.console?pullRequest=233) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spectresystems/spectre.console?pullRequest=233) it.</sub>

2021-01-14 16:46 UTC, patriksvensson commented
@NickWingate Great idea. Could we change this to accept a style instead, i.e. `HightlightStyle`? That way we're not limited to only colors.

2021-01-14 17:47 UTC, NickWingate commented
Changed HighlightColor to HighlightStyle, didn't think of that thanks!

2021-01-14 20:14 UTC, patriksvensson requested changes

2021-01-14 20:14 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Prompt/MultiSelectionPromptExtensions.cs
> +        /// Sets the highlight color of the selected choice.
```suggestion
        /// Sets the highlight style of the selected choice.
```

2021-01-14 20:14 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Prompt/SelectionPromptExtensions.cs
> +        /// Sets the highlight color of the selected choice.
```suggestion
        /// Sets the highlight style of the selected choice.
```

2021-01-14 21:38 UTC, NickWingate reviewed
Thanks for fixing the two comments I missed

2021-01-15 14:22 UTC, patriksvensson approved these changes

2021-01-15 14:23 UTC, merged

2021-01-15 14:23 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍