using loop instead of linq
spectresystems/spectre.console pull request #275
Opened 2021-02-27 05:26 UTC by phil-scott-78

In both loops, the context is captured preventing caching of the lambda. this results in a pretty significant number of allocations especially with progress bars that constantly are remeasuring

I noticed this while working on the update panel. over a 2-minute-long progress I was seeing a half gig worth of allocations there. After measuring it I noticed a huge portion of the allocations come from these two `Sum` functions. To keep it simple for this I just measured the allocs for the progress example

## before
![before](https://user-images.githubusercontent.com/2447331/109376281-7b59b600-7891-11eb-9f93-39cc1c24bb93.PNG)

## after
![after](https://user-images.githubusercontent.com/2447331/109376282-7dbc1000-7891-11eb-8a98-8c022ae533dd.PNG)

if you check the right-hand side you can see 9mb worth of allocations are gone for even just a 6s run.  For the 2-minute-long version run of the update panel it cut about 320mb out of 500mb.

2021-02-27 15:47 UTC, patriksvensson requested changes
Awesome! Performance is something we really need to look into and this is a great first step in reducing allocations! 👍🏻 

Found one minor thing that I think needs to be fixed though.

2021-02-27 15:47 UTC, patriksvensson commented on src/Spectre.Console/Rendering/Segment.cs
> +            Text = text.NormalizeNewLines() ?? throw new ArgumentNullException(nameof(text));
I think we still want the `text?` part since a `text` that is null will throw a null reference exception here.

```suggestion
            Text = text?.NormalizeNewLines() ?? throw new ArgumentNullException(nameof(text));
```

2021-02-27 16:09 UTC, phil-scott-78 commented on src/Spectre.Console/Rendering/Segment.cs
> +            Text = text.NormalizeNewLines() ?? throw new ArgumentNullException(nameof(text));
text would have had to be defined as `string?` to require a null check here, right?  But that change doesn't belong in this commit regardless. Ripped it out plus a whitespace change that snuck in.

2021-02-27 16:12 UTC, patriksvensson commented on src/Spectre.Console/Rendering/Segment.cs
> +            Text = text.NormalizeNewLines() ?? throw new ArgumentNullException(nameof(text));
@phil-scott-78 Correct, but since Segment is a public API, we can't guarantee that someone doesn't call the method with a null string if nullable reference types are turned off.

2021-02-27 16:12 UTC, patriksvensson approved these changes

2021-03-01 07:22 UTC, merged

2021-03-01 07:23 UTC, patriksvensson commented
@phil-scott-78 Merged! 👍