Replaces emoji regex with ReadOnlySpan implementation
spectresystems/spectre.console pull request #336
Opened 2021-04-03 01:54 UTC by phil-scott-78

The RegEx runtime perf was never anything noticeable - it was the startup time that was eating over a third of time during initialization. 
 This shaves 200ms off the startup time.

![image](https://user-images.githubusercontent.com/2447331/113464863-e2710a00-93fd-11eb-971a-56fe6eeddbb0.png)

I tried to add as many tests of combinations as possible and the sample apps and things seem to be working just as originally, but if you could hammer on it and try to break it. 

Double check my `ifdef` for netstandard too. It's a little ugly, but should keep netstandard 2.0 support chugging along.

2021-04-03 09:11 UTC, patriksvensson requested changes
Other than some minor stuff, this looks very good. Great work!

2021-04-03 12:30 UTC, phil-scott-78 commented
Great feedback and I appreciate it! I added an extension method but named it `AppendSpan` just so there wasn't a conflict with newer frameworks which already have the `Append`. 

Amended the commit and pushed the changes up.

2021-04-04 02:10 UTC, patriksvensson approved these changes

2021-04-04 02:10 UTC, merged

2021-04-04 02:10 UTC, patriksvensson commented
Merged 👍